---
include:
- board: eyelash_sofle_left
  shield: sofle_left
  artifact-name: eyelash_sofle_left
- board: eyelash_sofle_right
  shield: sofle_right
  artifact-name: eyelash_sofle_right
- board: nice_nano_v2
  shield: settings_reset
